### ISSUE TITLE
Issue with JSON POST requests

### ISSUE THREAD

**Issue by tworzenieweb** [bazzline/php_component_curl#2]
Hi Stev,

I've just found that there is an issue with sending post requests with json as content type using this component.

The first problem is the fact that default header

```
'application/x-www-form-urlencoded; charset=UTF-8'
```

is always set in 

https://github.com/bazzline/php_component_curl/blob/master/source/Request/RequestFactory.php#L80

so even if you use asJson() method in builder it will have two different content type headers.

```
'application/json'
'application/x-www-form-urlencoded; charset=UTF-8'
```

And because the default one is the last one then it is overriding json content type.

Lastly if request is of json type then `ConvertJsonToArrayBehaviour` is called after performing the request.

But there at line https://github.com/bazzline/php_component_curl/blob/master/source/ResponseBehaviour/ConvertJsonToArrayBehaviour.php#L24

json_encode function is triggered instead of json_decode.

As a workaround user can call `Builder::reset(true)` method after builder `create` method to just have this headers empty and then use asJson to make the valid content type.

But there is no way to fetch the correct response content since original json content is encoded once again after fetchin instead of `json_decode`ing.

Regards
Luke

**Comment by stevleibelt** [comment]
For the first "quick win", I've merged your [pull request](https://github.com/bazzline/php_component_curl/pull/3). Thanks for that.

For the default header issue, I have to think about it but you are absolutely right. This is a bad bug and I will take care as soon as possible.

**Comment by stevleibelt** [comment]
Finally fixed in the reported "form issue" in [version 0.14.0](https://github.com/bazzline/php_component_curl/tree/0.14.0).
I removed the default content type setting so "you" are now in charge to set the fitting one (except if you use the builder method _asJson_).

Thanks for reporting the bugs.

**Comment by seanperilous** [comment]
> For the first "quick win", I've merged your [pull request](https://github.com/bazzline/php_component_curl/pull/3). Thanks for that.
> 
> For the default header issue, I have to think about it but you are absolutely right. This is a bad bug and I will take care as soon as possible.





https://boycott-shortsighted4.github.io/m602RVhHL0AjyAO3U0oY6pcQHVcjTNJdMROShKiNoB4QE9frQvHwgNnuPZbvhiTIGrI/
